"""Runs every ALS_rewiring pipeline stage in order, stopping at the first failure.

    python -m exploration.analysis.ALS_rewiring_analysis                 # everything, stage 0 through 10
                                                                           # (incl. 05b)
    python -m exploration.analysis.ALS_rewiring_analysis --from 05       # resume from stage 05 (e.g. after
                                                                           # changing config and only wanting
                                                                           # to redo clustering onward)
    python -m exploration.analysis.ALS_rewiring_analysis --only 07 09    # just these two stages
    python -m exploration.analysis.ALS_rewiring_analysis --skip 02 08    # everything except these
                                                                           # (02 is diagnostic-only, 08 needs
                                                                           # network access and is slow)
    python -m exploration.analysis.ALS_rewiring_analysis --only 05b      # just the hierarchical re-clustering
                                                                           # stage (needs stage 05's output)

Stage 0 (`0_subset_d22.sh`/`0_subset_d35.sh`) generates config.D22_CSV/D35_CSV
from the raw S2GAE/STRING matrix if they don't already exist - both scripts
are idempotent (skip straight to a no-op if their output CSV is already
there), so it's safe and cheap to always run them first rather than requiring
that step be done manually beforehand.

Stage 05b (hierarchical re-clustering, see
`exploration.analysis.ALS_rewiring.hierarchical_recluster`) is a core,
required part of this pipeline - not optional or experimental - and always
runs between stage 05 and stage 06. It doesn't just produce diagnostics: it
OVERWRITES INTERMEDIATE_DIR's partition (giant.pickle's "module" attribute,
module_of.json, mod_ids.json, ...) with the hierarchically-refined one (after
backing up stage 05's original as module_of_pre_recluster.json/mod_ids_pre_
recluster.json), so stages 06-10 run downstream analysis on the refined
modules, not stage 05's original ones.

`neighborhood_by_context.py`/`neighborhood_new_gene_expression.py` run last,
for config.NEIGHBORHOOD_GENE (default: ALS2CL) against
config.NEIGHBORHOOD_EDGES_CSV - a neighborhood-edges CSV not generated by
this pipeline itself (see their own docstrings for where it comes from and
its caveats). They can still be re-run standalone for a different gene/CSV
via --gene/--csv, same as any other stage script.

Each stage is a standalone script under `ALS_rewiring/scripts/` that reads
its inputs from - and writes its outputs to - the on-disk intermediate/output
directories (see `exploration.analysis.ALS_rewiring.config`), so any stage
can also be re-run individually (`python exploration/analysis/ALS_rewiring/scripts/NN_stage_name.py`,
or `bash` for the stage-0 `.sh` scripts) without going through this
orchestrator at all.
"""
import argparse
import subprocess
import sys
from pathlib import Path

STAGES = [
    "0_subset_d22.sh",
    "0_subset_d35.sh",
    "01_load_merge_data.py",
    "02_validate_s2gae_scores.py",
    "03_select_high_confidence_edges.py",
    "04_build_giant_graph.py",
    "05_cluster_leiden.py",
    "05b_hierarchical_recluster.py",
    "06_module_enrichment.py",
    "07_condition_enrichment.py",
    "08_string_enrichment.py",
    "09_visualize_giant_network.py",
    "10_edge_components.py",
    "neighborhood_by_context.py",
    "neighborhood_new_gene_expression.py",
]

SCRIPTS_DIR = Path(__file__).resolve().parent / "ALS_rewiring" / "scripts"


def stage_id(name: str) -> str:
    return name.split("_", 1)[0]


def stage_command(stage: str) -> list:
    path = str(SCRIPTS_DIR / stage)
    return ["bash", path] if stage.endswith(".sh") else [sys.executable, path]


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--from", dest="from_stage", default=None, metavar="NN",
                         help="Start from this stage id (e.g. 05) and run to the end.")
    parser.add_argument("--only", nargs="+", default=None, metavar="NN",
                         help="Run only these stage ids.")
    parser.add_argument("--skip", nargs="+", default=None, metavar="NN",
                         help="Run every stage except these ids.")
    args = parser.parse_args()

    stages = STAGES
    if args.from_stage:
        stages = [s for s in stages if stage_id(s) >= args.from_stage]
    if args.only:
        stages = [s for s in stages if stage_id(s) in args.only]
    if args.skip:
        stages = [s for s in stages if stage_id(s) not in args.skip]

    if not stages:
        print("No stages selected - check --from/--only/--skip.")
        sys.exit(1)

    print("Running stages:", ", ".join(stages))
    for stage in stages:
        print(f"\n{'=' * 60}\n{stage}\n{'=' * 60}")
        result = subprocess.run(stage_command(stage))
        if result.returncode != 0:
            print(f"\nStage {stage} failed (exit code {result.returncode}) - stopping.")
            sys.exit(result.returncode)

    print("\nPipeline complete.")


if __name__ == "__main__":
    main()
