"""Model specifications for pretraining checkpoint evaluation."""

K_NEGATIVES = [1, 10, 50, 100, 500]
NEGATIVE_BANK_SIZE = max(K_NEGATIVES)

CORE_MODEL_ORDER = [
    "pinnacle_random",
    "pinnacle_esm2_acm",
    "pinnacle_esm2",
    "gae_att",
    "s2gae_att_k1_uni",
]
LOSS_MODEL_ORDER = [
    "s2gae_att_k1_uni",
    "s2gae_att_k1_l1_do00",
    "s2gae_att_k1_phuber",
]
POOLING_MODEL_ORDER = ["gae_att", "gae_vn", "gae_learnedvn"]
TABLE2_MODEL_ORDER = [
    "pinnacle_random",
    "pinnacle_esm2",
    "pinnacle_esm2_acm",
    "gae_att",
    "gae_att_uni",
    "gae_vn",
    "gae_vn_uni",
    "gae_learnedvn",
    "gae_learnedvn_uni",
    "s2gae_att_k1_no_uni",
    "s2gae_att_k1_uni",
]

MODELS = {
    "pinnacle_random": {
        "checkpoint": "pinnacle_random_gat_state_dict.pt",
        "name": "PINNACLE random fixed drop02",
        "short_name": "PINNACLE random",
        "kind": "pinnacle",
        "k_values": K_NEGATIVES,
        "encoder_pooling": "GATv2",
        "uniformity": None,
    },
    "pinnacle_esm2_acm": {
        "checkpoint": "pinnacle_esm2_acm_randomwalk_state_dict.pt",
        "name": "PINNACLE ESM2 ACM H64 drop02",
        "short_name": "PINNACLE ESM ACM",
        "kind": "pinnacle",
        "k_values": K_NEGATIVES,
        "encoder_pooling": "ACM",
        "uniformity": None,
    },
    "pinnacle_esm2": {
        "checkpoint": "pinnacle_esm2_gat_state_dict.pt",
        "name": "PINNACLE ESM2 fixed drop02",
        "short_name": "PINNACLE ESM2",
        "kind": "pinnacle",
        "k_values": K_NEGATIVES,
        "encoder_pooling": "GATv2",
        "uniformity": None,
    },
    "gae_att": {
        "checkpoint": "protscape_gae_state_dict.pt",
        "name": "GAE att fixed do06",
        "short_name": "GAE att",
        "kind": "protscape",
        "k_values": K_NEGATIVES,
        "metagraph": True,
        "encoder_pooling": "Attention",
        "uniformity": False,
    },
    "gae_att_uni": {
        "checkpoint": "protscape_gae_uniformity_state_dict.pt",
        "name": "GAE att fixed do06 uni5e-5",
        "short_name": "GAE att + uniformity",
        "kind": "protscape",
        "k_values": [1],
        "metagraph": True,
        "encoder_pooling": "Attention",
        "uniformity": True,
    },
    "gae_vn": {
        "checkpoint": "protscape_gae_virtual_node_state_dict.pt",
        "name": "GAE VN fixed do04",
        "short_name": "GAE VN",
        "kind": "protscape",
        "k_values": [1],
        "metagraph": True,
        "encoder_pooling": "VN",
        "uniformity": False,
    },
    "gae_vn_uni": {
        "checkpoint": "protscape_gae_virtual_node_uniformity_state_dict.pt",
        "name": "GAE VN fixed do04 uni5e-5",
        "short_name": "GAE VN + uniformity",
        "kind": "protscape",
        "k_values": [1],
        "metagraph": True,
        "encoder_pooling": "VN",
        "uniformity": True,
    },
    "gae_learnedvn": {
        "checkpoint": "protscape_gae_learned_virtual_node_state_dict.pt",
        "name": "GAE learnedVN fixed do06",
        "short_name": "GAE LVN",
        "kind": "protscape",
        "k_values": [1],
        "metagraph": True,
        "encoder_pooling": "LVN",
        "uniformity": False,
    },
    "gae_learnedvn_uni": {
        "checkpoint": "protscape_gae_learned_virtual_node_uniformity_state_dict.pt",
        "name": "GAE learnedVN fixed do06 uni5e-5",
        "short_name": "GAE LVN + uniformity",
        "kind": "protscape",
        "k_values": [1],
        "metagraph": True,
        "encoder_pooling": "LVN",
        "uniformity": True,
    },
    "s2gae_att_k1_no_uni": {
        "checkpoint": "protscape_no_uniformity_state_dict.pt",
        "name": "S2GAE att k=1 fixed do04",
        "short_name": "S2GAE k=1",
        "kind": "protscape",
        "k_values": [1],
        "metagraph": True,
        "encoder_pooling": "Attention",
        "uniformity": False,
    },
    "s2gae_att_k1_uni": {
        "checkpoint": "protscape_main_state_dict.pt",
        "name": "S2GAE att k=1 fixed do04 uni5e-5",
        "short_name": "S2GAE k=1 uni",
        "kind": "protscape",
        "k_values": K_NEGATIVES,
        "metagraph": True,
        "encoder_pooling": "Attention",
        "uniformity": True,
    },
    "s2gae_att_k1_phuber": {
        "checkpoint": "protscape_phuber_state_dict.pt",
        "name": "S2GAE att k=1 fixed do04 pHuber uni",
        "short_name": "S2GAE pHuber",
        "kind": "protscape",
        "k_values": K_NEGATIVES,
    },
    "s2gae_att_k1_l1_do00": {
        "checkpoint": "protscape_l1_state_dict.pt",
        "name": "S2GAE att k=1 fixed do00 L1 uni",
        "short_name": "S2GAE L1",
        "kind": "protscape",
        "k_values": K_NEGATIVES,
    },
}
