data_root: /storage/research/dbmr_luisierlab/database/PINNACLE/data
networks_bulk: /storage/research/dbmr_luisierlab/database/PINNACLE/data/networks_bulk
global_ppi: /storage/research/dbmr_luisierlab/database/PINNACLE/networks/global_ppi_edgelist.txt
inference_root: /storage/research/dbmr_luisierlab/database/PINNACLE/inference
output_root: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo
checkpoint_root: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/release_checkpoints
downstream_checkpoint_root: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/release_checkpoints/downstream
protscape_bce_checkpoint: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/release_checkpoints/protscape_main_state_dict.pt
protscape_gae_checkpoint: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/release_checkpoints/protscape_gae_state_dict.pt
protscape_gae_uniformity_checkpoint: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/release_checkpoints/protscape_gae_uniformity_state_dict.pt
protscape_gae_virtual_node_checkpoint: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/release_checkpoints/protscape_gae_virtual_node_state_dict.pt
protscape_gae_virtual_node_uniformity_checkpoint: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/release_checkpoints/protscape_gae_virtual_node_uniformity_state_dict.pt
protscape_gae_learned_virtual_node_checkpoint: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/release_checkpoints/protscape_gae_learned_virtual_node_state_dict.pt
protscape_gae_learned_virtual_node_uniformity_checkpoint: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/release_checkpoints/protscape_gae_learned_virtual_node_uniformity_state_dict.pt
protscape_no_uniformity_checkpoint: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/release_checkpoints/protscape_no_uniformity_state_dict.pt
protscape_phuber_checkpoint: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/release_checkpoints/protscape_phuber_state_dict.pt
protscape_l1_checkpoint: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/release_checkpoints/protscape_l1_state_dict.pt
pinnacle_random_checkpoint: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/release_checkpoints/pinnacle_random_gat_state_dict.pt
pinnacle_esm2_gat_checkpoint: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/release_checkpoints/pinnacle_esm2_gat_state_dict.pt
pinnacle_esm2_acm_checkpoint: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/release_checkpoints/pinnacle_esm2_acm_randomwalk_state_dict.pt

tabula_h5ad: /storage/research/dbmr_luisierlab/database/Tabula_Sapiens_v1/GSM6058681_TabulaSapiens.h5ad
tabula_metadata: /storage/research/dbmr_luisierlab/database/Tabula_Sapiens_v1/GSM6058681_TabulaSapiens_metadata.csv
hbca_neurons_h5ad: /storage/research/dbmr_luisierlab/database/HBCA_v1/HBCA_v1_all_neurons.h5ad
hbca_nonneurons_h5ad: /storage/research/dbmr_luisierlab/database/HBCA_v1/HBCA_v1_all_non_neuronal.h5ad
hbca_gene_metadata: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/input_data/hbca_gene_metadata.csv
als_gene_metadata: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/input_data/als_gene_metadata.csv

cell_ontology_obo: /storage/research/dbmr_luisierlab/database/PINNACLE/ontologies/cl-full.obo
tissue_ontology_obo: /storage/research/dbmr_luisierlab/database/PINNACLE/ontologies/bto.obo
celltype_class_mapping: /storage/research/dbmr_luisierlab/database/PINNACLE/data/networks_bulk/celltype_class_mapping.csv

als_motor_neuron_counts: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/input_data/als_motor_neuron_counts.csv
als_motor_neuron_metadata: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/input_data/als_motor_neuron_metadata.csv
als_astrocyte_counts: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/input_data/als_astrocyte_counts.csv
als_astrocyte_metadata: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/input_data/als_astrocyte_metadata.csv

cellphonedb_database: /storage/homefs/at25c279/.cpdb/releases/v3.0.0/cellphone.db

protein_sequences: /storage/research/dbmr_luisierlab/temp/athomas/ProtScape_release/data/sequence_embeddings/protein_sequences.csv.gz
esm2_embeddings: /storage/research/dbmr_luisierlab/database/PINNACLE/data/protein_gene_based_embeddings/gene_protein_embeddings_esm2_650M.plk
prostt5_embeddings: /storage/research/dbmr_luisierlab/database/PINNACLE/data/protein_gene_based_embeddings/gene_protein_embeddings_prostt5_1024.plk
pinnacle_paper_embeddings_dir: /storage/research/dbmr_luisierlab/database/PINNACLE/pinnacle_embeds
corum_raw_json: /storage/research/dbmr_luisierlab/database/PINNACLE/data/downstream_tasks/corum_dataset/corum_humanComplexes.json
corum_dataset_dir: /storage/research/dbmr_luisierlab/database/PINNACLE/data/downstream_tasks/corum_dataset
therapeutic_target_drugbank_targets: /storage/research/dbmr_luisierlab/database/PINNACLE/data/downstream_tasks/therapeutic_target_dataset/all_approved_oct2022.csv
therapeutic_target_evidence_dir: /storage/research/dbmr_luisierlab/database/PINNACLE/data/downstream_tasks/therapeutic_target_dataset/evidence_data/ot_24_03_evidence_chembl
therapeutic_target_dataset_dir: /storage/research/dbmr_luisierlab/database/PINNACLE/data/downstream_tasks/therapeutic_target_dataset

string_protein_info: /storage/research/dbmr_luisierlab/temp/athomas/.cache/stringdb/9606.protein.info.v12.0.txt.gz
string_links_detailed: /storage/research/dbmr_luisierlab/temp/athomas/.cache/stringdb/9606.protein.links.detailed.v12.0.txt.gz
string_protein_aliases: /storage/research/dbmr_luisierlab/temp/athomas/outputs/reference_cache/string_v12_human/9606.protein.aliases.v12.0.txt.gz
string_enrichment_terms: /storage/research/dbmr_luisierlab/temp/athomas/outputs/reference_cache/string_v12_human/9606.protein.enrichment.terms.v12.0.txt.gz
parkinson_external_support: /storage/research/dbmr_luisierlab/temp/athomas/outputs_protscape_repo/input_data/parkinson_external_support.csv
